name: Fly Deploy
on:
  push:
    branches: [ main ]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  test:
      name: Test the app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: yarn
        - run: yarn test
  deploy:
      name: Deploy app
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
